In [1]:
import numpy as np
# print(np.__version__)

## Multidimensional Array 🧊

In [2]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

print(array.ndim) # In ra loại mảng N chiều (0,1,2,3,...)
print(array.shape) # Trả về (depth, num rows, num cols)
print(array[0, 0, 0]) # Multidimensional indexing. Thay vì array[0][0][0]

#TODO: Hãy làm tên của mình và in ra
word = array[0, 0, 2] + array[0, 2, 1] + array[0, 2, 2] + array[1, 1, 1] + array[0, 2, 1]
print(word)

3
(3, 3, 3)
A
CHINH


## Slicing ✂️

In [3]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# array[start:end:step]
print(array[::2])
print(array[:, 0])
print(array[:, 0:3])
print(array[:, 1::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 1  5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


## Arithmetic ✖

In [4]:
# Scaler arithmetic

array = np.array([1, 2, 3])
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [5]:
# Vectorized math func

array = np.array([1.01, 2.5, 3.39])

print(np.sqrt(array))
print(np.round(array, 1))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)

[1.00498756 1.58113883 1.84119526]
[1.  2.5 3.4]
[1. 2. 3.]
[2. 3. 4.]
3.141592653589793


In [6]:
# Element wise arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [7]:
# Comparision operators

scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100)
print(scores >= 60)

[False False  True False False False]
[ True False  True  True  True  True]


## Broadcasting 📡

Phát sóng cho phép NumPy thực hiện các hoạt động trên mảng
với các hình dạng khác nhau bằng cách mở rộng kích thước thực tế
vì vậy chúng phù hợp với hình dạng của mảng lớn hơn.

Các kích thước có cùng kích thước.
```HOẶC```
Một trong các chiều có kích thước là 1.

### Nguyên tắc

1. So sánh shape từ phải sang trái (tức là từ chiều cuối cùng).

2. Hai chiều được coi là tương thích nếu:

    - Chúng bằng nhau, hoặc

    - Một trong hai bằng 1.

3. Nếu sau khi so sánh, tất cả các chiều đều tương thích, thì NumPy sẽ tự động “nhân bản ảo” (không tạo dữ liệu thật) mảng nhỏ hơn thành shape của mảng lớn hơn.

In [5]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape) # (4, 4)
print(array2.shape) # (4, 1)

print(array1 * array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


## Aggregate functions 📊

- Summarize data and typically
- return a single value

In [6]:
data = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

print(np.sum(data))
print(np.mean(data)) # Số trung bình
print(np.std(data)) # Độ lệch chuẩn (Standard Deviation)
print(np.var(data)) # Phương sai (Variance) = bình phương độ lệch chuẩn
print(np.min(data))
print(np.max(data))
print(np.argmin(data)) # Vị trí của số nhỏ nhất
print(np.argmax(data)) # Vị trí của số lớn nhất
print(np.sum(data, axis=0)) # axis = 0 là cột, axis = 1 là hàng

55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]


## Filtering 🧲


Refers to the process of selecting elements from an array that match the given condition

In [10]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 32, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages <65)] # dùng & cho and và | cho or. Vì numpy dùng giống C
seniors = ages[ages >= 65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]

print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

# Để giữ lại mảng nguyên dạng array thì dùng np.where. TODO: chỉ nên dùng nếu muốn giữ shape của mảng
adults = np.where(ages >= 18, ages, 0) # x là mảng dùng, y sẽ là fill value cho các giá trị không hợp lệ
print(adults)

[17 16 15]
[21 19 20 30 18 39 32 18 19 20 21]
[65 99]
[20 16 30 18 32 18 20]
[21 17 19 65 39 15 99 19 21]
[[21  0 19 20  0 30 18 65]
 [39 32  0 99 18 19 20 21]]


## Random numbers 🎲

In [11]:
rng = np.random.default_rng(seed=1) # rng = random number generator. Set seed để có kết quả giống

# Random integers
print(rng.integers(low=1, high=101, size=(3, 2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [12]:
# Random float
np.random.seed(1)
print(np.random.uniform(low=-1, high=1, size=(3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [13]:
# Shuffle array
rng = np.random.default_rng()

array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[1 5 4 3 2]


In [14]:
# Random choices
rng = np.random.default_rng()

fruits = np.array(["🍎", "🍊", "🍌", "🥥", "🍍"])
fruits = rng.choice(fruits, size=(3, 3))

print(fruits)

[['🍊' '🍎' '🍊']
 ['🍎' '🍊' '🍎']
 ['🍎' '🍌' '🥥']]
